language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5

addons:
  apt:
    packages:
      mlocate
          
install:
  - pip install git+git://github.com/spacetelescope/asv.git@master --user

script:
  - yes "" | asv machine
  - asv run -q master
