python:
  - 2.7
  - 3.4
  - 3.5

install:
  - sudo apt-get install mlocate
  - sudo pip install git+git://github.com/spacetelescope/asv.git@master

script:
  - yes "" | asv machine
  - asv run -q master
